### ISSUE TITLE
Tracy bar for this extension

### ISSUE THREAD

**Issue by h4kuna** [contributte/gosms#16]
I plan to make tracy bar, like list of sql querie, but list of send messeges for development.

In my case, the messages are send by rabbit, it is mean, the log must to save any storage and logger for tracy bar, will be read from this storage.

I have idea how to make. Have you any notes?

Could I implement any psr standard?

**Comment by h4kuna** [comment]
Where can i take icon for extension?

**Comment by f3l1x** [comment]
I usually pick one of here https://www.flaticon.com/

**Comment by h4kuna** [comment]
Všiml jsem si, že lze zaznamenávat požadavky a odpovědi (requests & response) pomocí [handleru v guzzle](https://github.com/contributte/guzzlette/blob/master/src/ClientFactory.php#L31) Asi to vyřeším tím že napíšu nějaký handler který bude ukládat na disk (či jiná storage) a zase z něj číst.

**Comment by f3l1x** [comment]
Pecka. Kdyz to udelas primo do guzlette, tak to budou mit vsichni co pouzivaji guzzle. Ja treba nepouzivam nic jineho.
