### ISSUE TITLE
AccessToken::isExpired

### ISSUE THREAD

**Issue by radimvaculik** [contributte/gosms#5]
Hi, 

could someone explain me this line?

https://github.com/contributte/gosms/blob/8c8d8cf8943a088d8a206565b7d72747f5938176/src/Entity/AccessToken.php#L36

Why does the line contains `modify('-5 minutes')` ? Forgotten debug or another reason?

Thanks, 

R.

**Comment by f3l1x** [comment]
There was a plan to implement refreshing using `refresh token`. So `-5 minutes` was so type of safety to have time to refresh it. Nothing more.

**Comment by radimvaculik** [comment]
Thanks, @f3l1x .
